name: All tools CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Filter commit changes
    outputs:
      all-tools: ${{ steps.filter.outputs.all-tools }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Filter commit changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          list-files: "json"
          filters: |
            all-tools:
              - 'operations/**'
              - '.github/workflows/all-tools.yml'
              - '.github/workflows/reuse-*.yml'

  store_image_name_and_tags:
    uses: ./.github/workflows/reuse-store-image-name-and-tags.yml
    with:
      image_name: consensys/linea-alltools

  check_image_tags_exist:
    needs: [ changes, store_image_name_and_tags ]
    if: ${{ needs.changes.outputs.all-tools == 'false' }}
    uses: ./.github/workflows/reuse-check-image-tags-exist.yml
    with:
      last_commit_tag: ${{ needs.store_image_name_and_tags.outputs.last_commit_tag }}
      common_ancestor_tag: ${{ needs.store_image_name_and_tags.outputs.common_ancestor_tag }}
      image_name: ${{ needs.store_image_name_and_tags.outputs.image_name }}
    secrets: inherit

  all-tools-tag-only:
    needs: [ changes, store_image_name_and_tags, check_image_tags_exist ]
    if: ${{ github.event_name != 'pull_request' && needs.changes.outputs.all-tools == 'false' }}
    uses: ./.github/workflows/reuse-image-tag-push.yml
    with:
      commit_tag: ${{ needs.store_image_name_and_tags.outputs.commit_tag }}
      last_commit_tag: ${{ needs.store_image_name_and_tags.outputs.last_commit_tag }}
      common_ancestor_tag: ${{ needs.store_image_name_and_tags.outputs.common_ancestor_tag }}
      develop_tag: ${{ needs.store_image_name_and_tags.outputs.develop_tag }}
      untested_tag_suffix: ${{ needs.store_image_name_and_tags.outputs.untested_tag_suffix }}
      image_name: ${{ needs.store_image_name_and_tags.outputs.image_name }}
      last_commit_tag_exists: ${{ needs.check_image_tags_exist.outputs.last_commit_tag_exists }}
      common_ancestor_commit_tag_exists: ${{ needs.check_image_tags_exist.outputs.common_ancestor_commit_tag_exists }}
    secrets: inherit

  build-and-publish:
    needs: [ changes, store_image_name_and_tags, all-tools-tag-only ]
    if: ${{ always() && (needs.changes.outputs.all-tools == 'true' || needs.all-tools-tag-only.result != 'success' || needs.all-tools-tag-only.outputs.image_tagged != 'true') }}
    runs-on: ubuntu-22.04
    env:
      COMMIT_TAG: ${{ needs.store_image_name_and_tags.outputs.commit_tag }}
      DEVELOP_TAG: ${{ needs.store_image_name_and_tags.outputs.develop_tag }}
      IMAGE_NAME: ${{ needs.store_image_name_and_tags.outputs.image_name }}
    name: All tools build and push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SELF_GITHUB_SSH_KEY }}
          submodules: true
          persist-credentials: false
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Note: Building arm* images on QEMU emulator can get extremely slow
      # when downloading large packages with npm / yarn. Arm* based docker
      # images are not necessarily needed as we run amd64 machines for most
      # cases. We can later set up self-hosted arm64 github runners if we
      # want arm* based images back.
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      #   with:
      #     platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Show the "version" build argument
        run: |
          echo "We inject the commit tag in the docker image ${{ env.COMMIT_TAG }}"
          echo COMMIT_TAG=${{ env.COMMIT_TAG }} >> $GITHUB_ENV
      - name: Build and push all tools image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./operations/Dockerfile
          platforms: linux/amd64
          # Note: Build amd64 image only
          # platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}
