name: Reusable check image tags exist
on:
  workflow_call:
    inputs:
      last_commit_tag:
        required: true
        type: string
      common_ancestor_tag:
        required: true
        type: string
      image_name:
        required: true
        type: string
    outputs:
      last_commit_tag_exists:
        value: ${{ jobs.check_image_tags_exist.outputs.last_commit_tag_exists }}
      common_ancestor_commit_tag_exists:
        value: ${{ jobs.check_image_tags_exist.outputs.common_ancestor_commit_tag_exists }}
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  check_image_tags_exist:
    runs-on: ubuntu-latest
    name: Check image tags exist
    continue-on-error: true
    env:
      LAST_COMMIT_TAG: ${{ inputs.last_commit_tag }}
      COMMON_ANCESTOR_TAG: ${{ inputs.common_ancestor_tag }}
      IMAGE_NAME: ${{ inputs.image_name }}
    outputs:
      last_commit_tag_exists: ${{ steps.last_commit_image_exists.outputs.last_commit_tag_exists }}
      common_ancestor_commit_tag_exists: ${{ steps.ancestor_commit_image_exists.outputs.common_ancestor_commit_tag_exists }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check last commit image tag exists
        id: last_commit_image_exists
        continue-on-error: true
        run: |
          echo last_commit_tag_exists=$(docker pull ${{ env.IMAGE_NAME }}:${{ env.LAST_COMMIT_TAG }} > /dev/null ; echo $?) >> $GITHUB_OUTPUT
      - name: Check ancestor commit image tag exists
        id: ancestor_commit_image_exists
        continue-on-error: true
        run: |
          echo common_ancestor_commit_tag_exists=$(docker pull ${{ env.IMAGE_NAME }}:${{ env.COMMON_ANCESTOR_TAG }} > /dev/null ; echo $?) >> $GITHUB_OUTPUT
      - name: Show outputs
        run: |
          echo "last_commit_tag_exists: ${{ steps.last_commit_image_exists.outputs.last_commit_tag_exists }}"
          echo "common_ancestor_commit_tag_exists: ${{ steps.ancestor_commit_image_exists.outputs.common_ancestor_commit_tag_exists }}"
