name: Reusable tag without untested suffix
on:
  workflow_call:
    inputs:
      commit_tag:
        required: true
        type: string
      develop_tag:
        required: true
        type: string
      untested_tag_suffix:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  tag-without-untested-suffix:
    runs-on: ubuntu-latest
    name: tag without untested suffix
    steps:
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker image with develop if on main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx imagetools create --tag ${{ inputs.image_name }}:${{ inputs.develop_tag }} ${{ inputs.image_name }}:${{ inputs.commit_tag }}-${{ inputs.untested_tag_suffix }}
      - name: Tag Docker image with the commit hash (without the "untested" suffix)
        run: |
          docker buildx imagetools create --tag ${{ inputs.image_name }}:${{ inputs.commit_tag }} ${{ inputs.image_name }}:${{ inputs.commit_tag }}-${{ inputs.untested_tag_suffix }}
