name: Reusable image tag and push
on:
  workflow_call:
    inputs:
      commit_tag:
        required: true
        type: string
      last_commit_tag:
        required: true
        type: string
      common_ancestor_tag:
        required: true
        type: string
      develop_tag:
        required: true
        type: string
      untested_tag_suffix:
        required: true
        type: string
      image_name:
        required: true
        type: string
      last_commit_tag_exists:
        required: true
        type: string
      common_ancestor_commit_tag_exists:
        required: true
        type: string
    outputs:
      image_tagged: 
        value: ${{ jobs.image_tag_push.outputs.image_tagged }}
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  image_tag_push:
    runs-on: ubuntu-latest
    name: image tag and push
    env:
      LAST_COMMIT_TAG: ${{ inputs.last_commit_tag }}
      COMMIT_TAG: ${{ inputs.commit_tag }}
      COMMON_ANCESTOR_TAG: ${{ inputs.common_ancestor_tag }}
      DEVELOP_TAG: ${{ inputs.develop_tag }}
      UNTESTED_TAG_SUFFIX: ${{ inputs.untested_tag_suffix }}
      LAST_COMMIT_TAG_EXISTS: ${{ inputs.last_commit_tag_exists }}
      COMMON_ANCESTOR_COMMIT_TAG_EXISTS: ${{ inputs.common_ancestor_commit_tag_exists }}
      IMAGE_NAME: ${{ inputs.image_name }}
    outputs:
      image_tagged: ${{ env.IMAGE_TAGGED }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Initialize IMAGE_TAGGED value
        run: |
          echo IMAGE_TAGGED=false >> $GITHUB_ENV
      - name: Tag Docker image with last commit tag with the commit hash plus w/o "untested" suffix
        if: ${{ env.LAST_COMMIT_TAG != '0000000' && env.LAST_COMMIT_TAG_EXISTS == '0' }}
        run: |
          docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }} ${{ env.IMAGE_NAME }}:${{ env.LAST_COMMIT_TAG }}
          docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}-${{ env.UNTESTED_TAG_SUFFIX }} ${{ env.IMAGE_NAME }}:${{ env.LAST_COMMIT_TAG }}
          echo IMAGE_TAGGED=true >> $GITHUB_ENV
      - name: Tag Docker image with common ancestor commit tag with the commit hash plus w/o "untested" suffix
        if: ${{ env.LAST_COMMIT_TAG == '0000000' && env.COMMON_ANCESTOR_COMMIT_TAG_EXISTS == '0' }}
        run: |
          docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }} ${{ env.IMAGE_NAME }}:${{ env.COMMON_ANCESTOR_TAG }}
          docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}-${{ env.UNTESTED_TAG_SUFFIX }} ${{ env.IMAGE_NAME }}:${{ env.COMMON_ANCESTOR_TAG }}
          echo IMAGE_TAGGED=true >> $GITHUB_ENV
      - name: Tag Docker image with develop if on main branch
        if: ${{ github.ref == 'refs/heads/main' && env.LAST_COMMIT_TAG_EXISTS == '0' }}
        run: |
          docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:${{ env.DEVELOP_TAG }} ${{ env.IMAGE_NAME }}:${{ env.LAST_COMMIT_TAG }}
          echo IMAGE_TAGGED=true >> $GITHUB_ENV