name: Smart contracts test

on:
  push:
    paths:
      - 'contracts/**'
      - 'testdata/**'

jobs:
  run-contract-tests:
    runs-on: ubuntu-latest
    name: Run smart contracts tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'pnpm'
      - name: Npm install
        run: pnpm i --frozen-lockfile --prefer-offline --ignore-scripts
      - name: Check JS formatting
        run: pnpm -F contracts run lint:ts
      - name: Run smart contracts tests and generate coverage report
        run: pnpm -F contracts run coverage

  solidity-format-check:
    runs-on: ubuntu-latest
    name: Solidity format check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'pnpm'
      - name: Npm install
        run: pnpm i --frozen-lockfile --prefer-offline --ignore-scripts
      - name: Check Solidity formatting
        run: pnpm -F contracts run lint:sol
