input_traces_directory = "/data/traces/raw"
output_traces_directory = "/data/traces/conflated"
traces_version = "0.2.0"
traces_file_extension = "json.gz"

# Inmemory cache of the traces read from the file system
# Save IO and  CPU unzipping and JSON parsing
[read_traces_cache]
size = 20
expiration_duration = "PT20M"

[api]
port = 8080
path = "/"
# if =0, it will create one verticle per core (or hyperthread if supported)
number_of_verticles = 0
observability_port = 8090
