##
# Smart contract error codes from:
# https://www.notion.so/consensys/Smart-Contracts-Error-Code-Registry-bb4bd68f8ddf4b0ba90000d1136e42ef
##

[smart-contract-errors]
"0F06CD15" = "DataAlreadySubmitted"
"D5AA5AD6" = "StateRootHashInvalid"
"C01EAB56" = "EmptySubmissionData"
"DCB23885" = "FinalizationDataMissing"
"ABEFA5E8" = "DataStartingBlockDoesNotMatch"
"9F6ADC69" = "DataEndingBlockDoesNotMatch"
"5548C6B3" = "DataParentHasEmptyShnarf"
"36459FA0" = "L1RollingHashDoesNotExistOnL1"
"3211D9BE" = "TimestampsNotInSequence"
"9C80BDEA" = "FinalBlockNumberInvalid"
"9A89A758" = "ParentHashesDoesNotMatch"
"E1CB6E60" = "FinalStateRootHashDoesNotMatch"
"710CD580" = "DataHashesNotInSequence"
"CBBD7953" = "FirstBlockGreaterThanFinalBlock"
"A386ED70" = "FirstBlockLessThanOrEqualToLastFinalizedBlock"
"70614405" = "FinalBlockNumberLessThanOrEqualToLastFinalizedBlock"
"2898482A" = "FinalBlockStateEqualsZeroHash"
"BF81C6E0" = "FinalizationInTheFuture"
"0C256592" = "MissingMessageNumberForRollingHash"
"5228F4C8" = "MissingRollingHashForMessageNumber"
"729EEBCE" = "FirstByteIsNotZero"
"6426C6C5" = "BytesLengthNotMultipleOf32"
"32BDD925" = "YPointGreaterThanCurveModulus"
"68DCAD5F" = "PointEvaluationResponseInvalid"
"F75DB381" = "PrecompileReturnDataLengthWrong"
"A71194AF" = "PointEvaluationFailed"
"A0FEAE8D" = "EmptyBlobData"
"2F22B98A" = "LastFinalizedShnarfWrong"
"4E686675" = "L2MerkleRootDoesNotExist"
"B05E92FA" = "InvalidMerkleProof"
"5E3FD6AD" = "ProofLengthDifferentThanMerkleDepth"
"9B0F0C28" = "SystemMigrationBlockZero"
"E5D14425" = "L2MerkleRootAlreadyAnchored"
"335A4A90" = "MessageAlreadyClaimed"
"0C91D776" = "BytesLengthNotMultipleOfTwo"
"D39E75F9" = "L1MessageNumberSynchronizationWrong"
"AC1775CF" = "ServiceHasMigratedToRollingHashes"
"7557A60A" = "L1RollingHashSynchronizationWrong"
"36A4BB94" = "FinalRollingHashIsZero"
"A75D20DB" = "BlockTimestampError"
"EAD4C30E" = "StartingRootHashDoesNotMatch"
"E98CFD2F" = "EmptyBlockDataArray"
"8999649C" = "EmptyBlock"
"7907D79B" = "ProofIsEmpty"
"69ED70AB" = "InvalidProofType"
"09BDE339" = "InvalidProof"
"8579BEFE" = "ZeroAddressNotAllowed"
"4124301E" = "MessageAlreadySent"
"992D87C3" = "MessageDoesNotExistOrHasAlreadyBeenClaimed"
"EE49E001" = "MessageAlreadyReceived"
"62A064C5" = "L1L2MessageNotSent"
"3B174434" = "MessageHashesListLengthHigherThanOneHundred"
"52E9BB24" = "EmptyMessageHashesArray"
"DB246DDE" = "IsPaused"
"B015579F" = "IsNotPaused"
"BAC5BF1B" = "TransactionShort"
"E95A14A6" = "UnknownTransactionType"
"06007832" = "NotList"
"FCED5668" = "NoNext"
"78268BBB" = "MemoryOutOfBounds"

