linters:
  disable-all: true
  enable:
    - gofmt
    - staticcheck
    - gosec
    - gosimple
    - govet
    - ineffassign

run:
  issues-exit-code: 1
  # List of build tags, all linters use it.
  # Default: [].
  build-tags:
    - nocorset
  skip-dirs:
    - compressor

linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1019' # disable the rule against deprecated code
