environment = "integration-full"
version = "2.0.0"                              # TODO @gbotrel hunt all version definitions.
assets_dir = "/opt/linea/prover/prover-assets"
log_level = 4                                  # TODO @gbotrel will be refactored with new logger. 

[controller]
retry_delays = [0, 1]

[execution]
prover_mode = "full"
features = { with_keccak = true, with_ecdsa = false }

[blob_decompression]
prover_mode = "dev"

[aggregation]
prover_mode = "full"
num_proofs = [10]
allowed_inputs = ["execution-dummy", "execution", "blob-decompression-dummy"]
verifier_id = 1

[layer2]
chain_id = 59144
message_service_contract = "0x508Ca82Df566dCD1B0DE8296e70a96332cD644ec"
