name: Run Bridge UI E2E Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'bridge-ui/**'
  push:
    branches:
      - main
    paths:
      - 'bridge-ui/**'

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bridge-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18.15.0
          cache: 'npm'
          cache-dependency-path: bridge-ui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install puppeteer dependencies
        run: sudo apt update && sudo apt install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2

      - name: Install chrome
        run: node ./node_modules/puppeteer/install.mjs

      - name: Build Bridge UI
        run: npm run build
        env:
          NEXT_PUBLIC_WALLET_CONNECT_ID: ${{ secrets.PUBLIC_WALLET_CONNECT_ID }}
          NEXT_PUBLIC_INFURA_ID: ${{ secrets.PUBLIC_BRIDGE_UI_INFURA_ID }}

      - name: Run tests
        run: npm test
        env:
          E2E_TEST_PRIVATE_KEY: ${{ secrets.BRIDGE_UI_E2E_TESTS_PRIVATE_KEY }}
